export const FETCH_TOYS_REQUEST = 'FETCH_TOYS_REQUEST';
export const FETCH_TOYS_SUCCESS = 'FETCH_TOYS_SUCCESS';
export const FETCH_TOYS_ERROR = 'FETCH_TOYS_ERROR';
export const ADD_NEW_LEGO = 'ADD_NEW_LEGO';