export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_ERROR = 'FETCH_GAMES_ERROR';
export const SEARCH_GAMES_REQUEST = 'SEARCH_GAMES_REQUEST';
export const CHANGE_ROUTER = 'CHANGE_ROUTER';